version: '3'
services:
  # PHP Service
  app:
    image: nrgnr/invoiceninja:local
    container_name: invoiceninja-app
    restart: unless-stopped
    tty: true
    environment:
      # Application settings
      APP_URL: http://localhost:9000
      REACT_URL: http://localhost:9000
      APP_DEBUG: 'false'
      APP_KEY: base64:RR++yx2rJ9kdxbdh3+AmbHLDQu+Q76i++co9Y8ybbno=
      NINJA_ENVIRONMENT: selfhost
      
      # Database settings
      DB_HOST: db
      DB_DATABASE: ninja
      DB_USERNAME: ninja
      DB_PASSWORD: ninja
      DB_PORT: 3306
      
      # Redis settings
      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
      
      # Cache and sessions
      BROADCAST_DRIVER: log
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: redis
      SESSION_LIFETIME: 120
      
      # PDF generator
      PDF_GENERATOR: hosted_ninja
    volumes:
      - ninja_storage:/var/www/storage
      - ninja_public:/var/www/public
    networks:
      - ninja_network
    depends_on:
      - db
      - redis

  # Caddy Service
  webserver:
    image: caddy:2-alpine
    container_name: invoiceninja-caddy
    restart: unless-stopped
    ports:
      - "9000:80"
    volumes:
      - ninja_public:/var/www/public
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - ninja_network
    depends_on:
      - app

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: invoiceninja-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ninja
      MYSQL_USER: ninja
      MYSQL_PASSWORD: ninja
      MYSQL_ROOT_PASSWORD: ninja_root
    volumes:
      - ninja_mysql:/var/lib/mysql
    networks:
      - ninja_network

  # Redis Service
  redis:
    image: redis:alpine
    container_name: invoiceninja-redis
    restart: unless-stopped
    networks:
      - ninja_network

# Networks
networks:
  ninja_network:
    driver: bridge

# Volumes
volumes:
  ninja_storage:
    driver: local
  ninja_public:
    driver: local
  ninja_mysql:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local 